---
global:
  resolve_timeout: 1m

route:
  receiver: 'blackhole'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

  routes:
    - match:
        severity: critical
      receiver: blackhole
      continue: false
      repeat_interval: 12h
    - match:
        severity: warning
      receiver: blackhole
      repeat_interval: 24h
      continue: false
    - match:
        severity: indeterminate
      receiver: blackhole
      repeat_interval: 48h
      continue: false

receivers:
- name: 'blackhole'
- name: 'web.hook'
  webhook_configs:
  - send_resolved: True
    url: 'http://localhost:9087/alert/-521575878'