---

- name: Opensearch installation & configuration
  hosts: os-cluster
  gather_facts: true
  roles:
    - { role: opensearch }

#- name: Opensearch dashboards installation & configuration
#  hosts: dashboards
#  gather_facts: true
#  roles:
#    - { role: dashboards }
