- hosts: all
  vars:
    prometheus_components:
      - prometheus
      - alertmanager
      - node_exporter
    prometheus_systemd_oom_score: "-1000"
    prometheus_host: "0.0.0.0"
    prometheus_port: 9090
    prometheus_extra_opts:
     - '--storage.tsdb.retention.time=1y'
     - '--storage.tsdb.retention.size=30GB'
    prometheus_logrotate: true
    prometheus_logrotate_count: 31
    prometheus_logrotate_compress: true
    prometheus_storage_dir: /opt/prometheus/var/prometheus
    prometheus_script_yum: true
    prometheus_server_cfg:
      global:
        scrape_interval: 15s
        external_labels:
          monitor: 'Prometheus monitoring system'
          service: Prometheus
      rule_files:
        - /etc/prometheus-rules.yml
      alerting:
        alertmanagers:
          - static_configs:
              - targets:
                  - localhost:9093
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 30s
          static_configs:
            - targets: [ 'd00prom0001:9090' ]
        - job_name: 'node_exporter'
          scrape_interval: 15s
          static_configs:
            - targets: [ 'd00prom0001:9100', 'd00elk0001:9100', 'd00psql0001:9100', 'd00redis0001:9100', 'd00keydb0001:9100', 'd00jaeger0001:9100', 'd00balancer0001:9100', 'd00app0001:9100', 'd00pgbouncer0001:9100', 'd00loader0001:9100', 'd00loki0001:9100' ]
          relabel_configs:
            - source_labels: [ '__address__' ]
              target_label: 'environment'
              replacement: 'production'
        - job_name: 'process_exporter'
          scrape_interval: 15s
          static_configs:
            - targets: [ 'd00prom0001:9256', 'd00elk0001:9256', 'd00psql0001:9256', 'd00redis0001:9256', 'd00keydb0001:9256', 'd00jaeger0001:9256', 'd00balancer0001:9256', 'd00app0001:9256','d00pgbouncer0001:9256', 'd00loader0001:9256', 'd00loki0001:9256' ]
          relabel_configs:
            - source_labels: [ '__address__' ]
              target_label: 'environment'
              replacement: 'staging'
        - job_name: 'alertmanager'
          scrape_interval: 30s
          static_configs:
            - targets: [ 'd00prom0001:9093' ]
          relabel_configs:
            - source_labels: [ '__address__' ]
              target_label: 'environment'
              replacement: 'staging'
        - job_name: 'redis_exporter'
          scrape_interval: 15s
          static_configs:
            - targets: [ 'd00redis0001:9121', 'd00keydb0001:9121', 'd00redis-sentinel0001:9121', 'd00redis-sentinel0002:9121', 'd00redis-sentinel0003:9121' ]
          relabel_configs:
            - source_labels: [ '__address__' ]
              target_label: 'environment'
              replacement: 'staging'
        - job_name: 'fluent_bit_exporter'
          scrape_interval: 15s
          metrics_path: /api/v1/metrics/prometheus
          static_configs:
            - targets: [ 'd00prom0001:2020', 'd00elk0001:2020', 'd00psql0001:2020', 'd00redis0001:2020', 'd00keydb0001:2020', 'd00jaeger0001:2020', 'd00balancer0001:2020', 'd00app0001:2020','d00pgbouncer0001:2020', 'd00loader0001:2020' ]
          relabel_configs:
            - source_labels: [ '__address__' ]
              target_label: 'environment'
              replacement: 'development'
  roles:
    - prometheus